apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: weather-dashboard-hpa
  namespace: weather-dashboard

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: weather-dashboard-deployment

  minReplicas: 1
  maxReplicas: 5

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 5

