kind: Pod
apiVersion: v1
metadata:
  name: load-generator
  namespace: weather-dashboard
  labels:
    app: weather-app-load

spec:
  containers:
    - name: load-generator-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args: 
      - |
        while true;
        do wget -q -O- http://weather-dashboard-service.weather-dashboard.svc.cluster.local:8000; 
        done
  restartPolicy: Always
