kind: Service
apiVersion: v1
metadata:
  name: weather-dashboard-service
#  namespace: weather-dashboard
  namespace: nginx
spec:
  selector:
    app: weather-app
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
  type: ClusterIP
